[component]
structures = [ "content_blocks" ]
label = "Hero"
description = "Page hero with the heading, description, buttons, and an image"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
title = "DDD East Midlands Conference"
description_html = ""
image = "/images/logo.png"
image_alt = "DDD East Midlands Conference logo"
cta_button: "LinkedIn"
cta_button_link: "https://www.linkedin.com/company/ddd-east-midlands-limited/"