name: DDDEMBlog

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        jekyll build
    - name: Set AWS CLI	
      env:	
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}	
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}	
      run: |
        sudo pip install --upgrade pip
        echo "pip upgraded"
        pip install --user awscli
        echo "AWS CLI installed"
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
        aws configure set region eu-west-2
        aws configure set output json
        echo "AWS CLI configured"
    - name: Deploy To S3
      run: |
        aws s3 sync ./_site/ s3://blog.dddeastmidlands.com/  --delete
        echo "Deployed to S3"
